### ISSUE TITLE
Have google phishlet?

### ISSUE THREAD

**Issue by Dazmed707** [fluxxset/Evilginx_monitor#1]
Have google phishlet for configure in Evilginx and Telegram?

**Comment by fluxxset** [comment]
#### ⚠️ IMPORTANT WARNING ⚠️

- DO NOT ASK FOR PHISHLETS.
- DO NOT ASK FOR HELP CREATING PHISHLETS.
- DO NOT ASK TO FIX PHISHLETS.
- DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.

**Comment by fluxxset** [comment]
#### ⚠️ IMPORTANT WARNING ⚠️

- DO NOT ASK FOR PHISHLETS.
- DO NOT ASK FOR HELP CREATING PHISHLETS.
- DO NOT ASK TO FIX PHISHLETS.
- DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.
