### ISSUE TITLE
Doesn't Send Session Cookies

### ISSUE THREAD

**Issue by ktrap-star** [fluxxset/Evilginx_monitor#2]
It doesn't send the session cookies to telegram. It sends only the username/password and session ID. Try to make it send the session cookies in a txt file to telegram bot as well as that will be great. This is really amazing. Thank you.
![git issue](https://github.com/user-attachments/assets/0ef8e72d-f157-4f53-a565-b6a4347c2886)

**Comment by fluxxset** [comment]
This issue has been fixed in [commit f55baabb0e9059dcab0480749a1a9ad3bb188c35](https://github.com/fluxxset/Evilginx_monitor/commit/f55baabb0e9059dcab0480749a1a9ad3bb188c35).

**Comment by DrakoTech1** [comment]
Hello please it doesnt work on my system. Am i getting the error of not attaching the evilginx database properly? Please kind help out i cant find any data.db in evilginx. Am using the evilginx from kgretzky and i cant find the db file pls kindly help ourt or what do i inout there? Also the monitor and evilginx i even put them in a single folder for it to work.
