### ISSUE TITLE
Can't monitor email password in Phishing Facebook

### ISSUE THREAD

**Issue by johnjork** [fluxxset/Evilginx_monitor#4]
I have a problem as below. Telegram Bot sent 3 messages continuously to Chat and failed to detect password and email.

Please help me check.

![image](https://github.com/user-attachments/assets/c177ca91-ed9e-4418-aace-779c66c0d4fd)
![image](https://github.com/user-attachments/assets/05d10541-ad32-4368-a403-94f743111ed3)

**Comment by fluxxset** [comment]
when you do `sessions` dose username and password comes up ?

**Comment by johnjork** [comment]
> when you do `sessions` dose username and password comes up ?

Not show. Please help me to check it

**Comment by fluxxset** [comment]
then its phishlet issue , not a plugin issuye
