### ISSUE TITLE
Failed to send email: EOF Error sending Mail notification: EOF

### ISSUE THREAD

**Issue by bigben2025** [fluxxset/Evilginx_monitor#5]
------------------------------------------------------
Failed to send email: EOF
Error sending Mail notification: EOF

my smtp info are correct

**Comment by fluxxset** [comment]
Bug has been identified fixing it .

**Comment by samwi11** [comment]
its not sending the data to telegram what the problem. i follow the exact steps that shown on the video.

**Comment by fluxxset** [comment]
its fixed now pls have a look
