### ISSUE TITLE
The evilginx monitor fails to capture

### ISSUE THREAD

**Issue by Jandre224** [fluxxset/Evilginx_monitor#8]
Hello, I've tried several times using the evilginx monitor to capture to telegram but it fails to capture, when I use my phishing lure and enter credentials, I'd be expecting the monitor to capture the credentials and send to my telegram but it fails to do so, it says in terminal that the file was renamed or removed when I tried to use the lure to capture credentials and it fails

**Comment by fluxxset** [comment]
can u attch screenshot of error , just tested and working fine .
https://fluxxset.com/t/evilginx-monitor-tool-not-working/309
